# Some default env vars.

env = XCURSOR_SIZE,24
env = QT_QPA_PLATFORMTHEME,qt5ct # change to qt6ct if you have that
env = THEME_BG,$color_bg
env = THEME_FG,$color_fg
env = THEME_ACCENT,$color_accent
env = THEME_ALERT,$color_alert